package ordappengine;

import java.io.Serializable;
import java.util.ArrayList;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;

@Entity(name = "User")
public class User implements Serializable {
	/**
	 * The serialVersionUID is generated by Java compiler
	 */
	private static final long serialVersionUID = 6811971274319075993L;
	@Id
	public String emailAddress;
	@Basic
	public String password;
	@Basic
	public boolean isAdmin = false;
	@Basic
	public ArrayList<Submission> submissions;

	public void addSubmission(Submission submission) {
		if (submissions == null)
			submissions = new ArrayList<Submission>();
		submissions.add(submission);
	}
}