/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-05 at 09:39:11 UTC 
 * Modify at your own risk.
 */

package ordappengine.ordappengine.networkendpoint;

/**
 * Service definition for Networkendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link NetworkendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Networkendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the networkendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://postermanagementsystem.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "networkendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Networkendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Networkendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "authenticateSession".
   *
   * This request holds the parameters needed by the the networkendpoint server.  After setting any
   * optional parameters, call the {@link AuthenticateSession#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public AuthenticateSession authenticateSession() throws java.io.IOException {
    AuthenticateSession result = new AuthenticateSession();
    initialize(result);
    return result;
  }

  public class AuthenticateSession extends NetworkendpointRequest<ordappengine.ordappengine.networkendpoint.model.BackendSession> {

    private static final String REST_PATH = "authenticateSession";

    /**
     * Create a request for the method "authenticateSession".
     *
     * This request holds the parameters needed by the the networkendpoint server.  After setting any
     * optional parameters, call the {@link AuthenticateSession#execute()} method to invoke the remote
     * operation. <p> {@link AuthenticateSession#initialize(com.google.api.client.googleapis.services.
     * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected AuthenticateSession() {
      super(Networkendpoint.this, "POST", REST_PATH, null, ordappengine.ordappengine.networkendpoint.model.BackendSession.class);
    }

    @Override
    public AuthenticateSession setAlt(java.lang.String alt) {
      return (AuthenticateSession) super.setAlt(alt);
    }

    @Override
    public AuthenticateSession setFields(java.lang.String fields) {
      return (AuthenticateSession) super.setFields(fields);
    }

    @Override
    public AuthenticateSession setKey(java.lang.String key) {
      return (AuthenticateSession) super.setKey(key);
    }

    @Override
    public AuthenticateSession setOauthToken(java.lang.String oauthToken) {
      return (AuthenticateSession) super.setOauthToken(oauthToken);
    }

    @Override
    public AuthenticateSession setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AuthenticateSession) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AuthenticateSession setQuotaUser(java.lang.String quotaUser) {
      return (AuthenticateSession) super.setQuotaUser(quotaUser);
    }

    @Override
    public AuthenticateSession setUserIp(java.lang.String userIp) {
      return (AuthenticateSession) super.setUserIp(userIp);
    }

    @Override
    public AuthenticateSession set(String parameterName, Object value) {
      return (AuthenticateSession) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getAllSubmissions".
   *
   * This request holds the parameters needed by the the networkendpoint server.  After setting any
   * optional parameters, call the {@link GetAllSubmissions#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public GetAllSubmissions getAllSubmissions() throws java.io.IOException {
    GetAllSubmissions result = new GetAllSubmissions();
    initialize(result);
    return result;
  }

  public class GetAllSubmissions extends NetworkendpointRequest<ordappengine.ordappengine.networkendpoint.model.SubmissionCollection> {

    private static final String REST_PATH = "submissioncollection";

    /**
     * Create a request for the method "getAllSubmissions".
     *
     * This request holds the parameters needed by the the networkendpoint server.  After setting any
     * optional parameters, call the {@link GetAllSubmissions#execute()} method to invoke the remote
     * operation. <p> {@link GetAllSubmissions#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetAllSubmissions() {
      super(Networkendpoint.this, "GET", REST_PATH, null, ordappengine.ordappengine.networkendpoint.model.SubmissionCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAllSubmissions setAlt(java.lang.String alt) {
      return (GetAllSubmissions) super.setAlt(alt);
    }

    @Override
    public GetAllSubmissions setFields(java.lang.String fields) {
      return (GetAllSubmissions) super.setFields(fields);
    }

    @Override
    public GetAllSubmissions setKey(java.lang.String key) {
      return (GetAllSubmissions) super.setKey(key);
    }

    @Override
    public GetAllSubmissions setOauthToken(java.lang.String oauthToken) {
      return (GetAllSubmissions) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAllSubmissions setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAllSubmissions) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAllSubmissions setQuotaUser(java.lang.String quotaUser) {
      return (GetAllSubmissions) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAllSubmissions setUserIp(java.lang.String userIp) {
      return (GetAllSubmissions) super.setUserIp(userIp);
    }

    @Override
    public GetAllSubmissions set(String parameterName, Object value) {
      return (GetAllSubmissions) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getSubmissions".
   *
   * This request holds the parameters needed by the the networkendpoint server.  After setting any
   * optional parameters, call the {@link GetSubmissions#execute()} method to invoke the remote
   * operation.
   *
   * @param emailAddress
   * @return the request
   */
  public GetSubmissions getSubmissions(java.lang.String emailAddress) throws java.io.IOException {
    GetSubmissions result = new GetSubmissions(emailAddress);
    initialize(result);
    return result;
  }

  public class GetSubmissions extends NetworkendpointRequest<ordappengine.ordappengine.networkendpoint.model.SubmissionCollection> {

    private static final String REST_PATH = "submissioncollection/{emailAddress}";

    /**
     * Create a request for the method "getSubmissions".
     *
     * This request holds the parameters needed by the the networkendpoint server.  After setting any
     * optional parameters, call the {@link GetSubmissions#execute()} method to invoke the remote
     * operation. <p> {@link GetSubmissions#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param emailAddress
     * @since 1.13
     */
    protected GetSubmissions(java.lang.String emailAddress) {
      super(Networkendpoint.this, "GET", REST_PATH, null, ordappengine.ordappengine.networkendpoint.model.SubmissionCollection.class);
      this.emailAddress = com.google.api.client.util.Preconditions.checkNotNull(emailAddress, "Required parameter emailAddress must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetSubmissions setAlt(java.lang.String alt) {
      return (GetSubmissions) super.setAlt(alt);
    }

    @Override
    public GetSubmissions setFields(java.lang.String fields) {
      return (GetSubmissions) super.setFields(fields);
    }

    @Override
    public GetSubmissions setKey(java.lang.String key) {
      return (GetSubmissions) super.setKey(key);
    }

    @Override
    public GetSubmissions setOauthToken(java.lang.String oauthToken) {
      return (GetSubmissions) super.setOauthToken(oauthToken);
    }

    @Override
    public GetSubmissions setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetSubmissions) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetSubmissions setQuotaUser(java.lang.String quotaUser) {
      return (GetSubmissions) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetSubmissions setUserIp(java.lang.String userIp) {
      return (GetSubmissions) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String emailAddress;

    /**

     */
    public java.lang.String getEmailAddress() {
      return emailAddress;
    }

    public GetSubmissions setEmailAddress(java.lang.String emailAddress) {
      this.emailAddress = emailAddress;
      return this;
    }

    @Override
    public GetSubmissions set(String parameterName, Object value) {
      return (GetSubmissions) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPoster".
   *
   * This request holds the parameters needed by the the networkendpoint server.  After setting any
   * optional parameters, call the {@link InsertPoster#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link ordappengine.ordappengine.networkendpoint.model.Submission}
   * @return the request
   */
  public InsertPoster insertPoster(ordappengine.ordappengine.networkendpoint.model.Submission content) throws java.io.IOException {
    InsertPoster result = new InsertPoster(content);
    initialize(result);
    return result;
  }

  public class InsertPoster extends NetworkendpointRequest<Void> {

    private static final String REST_PATH = "void";

    /**
     * Create a request for the method "insertPoster".
     *
     * This request holds the parameters needed by the the networkendpoint server.  After setting any
     * optional parameters, call the {@link InsertPoster#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertPoster#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link ordappengine.ordappengine.networkendpoint.model.Submission}
     * @since 1.13
     */
    protected InsertPoster(ordappengine.ordappengine.networkendpoint.model.Submission content) {
      super(Networkendpoint.this, "POST", REST_PATH, content, Void.class);
    }

    @Override
    public InsertPoster setAlt(java.lang.String alt) {
      return (InsertPoster) super.setAlt(alt);
    }

    @Override
    public InsertPoster setFields(java.lang.String fields) {
      return (InsertPoster) super.setFields(fields);
    }

    @Override
    public InsertPoster setKey(java.lang.String key) {
      return (InsertPoster) super.setKey(key);
    }

    @Override
    public InsertPoster setOauthToken(java.lang.String oauthToken) {
      return (InsertPoster) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPoster setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPoster) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPoster setQuotaUser(java.lang.String quotaUser) {
      return (InsertPoster) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPoster setUserIp(java.lang.String userIp) {
      return (InsertPoster) super.setUserIp(userIp);
    }

    @Override
    public InsertPoster set(String parameterName, Object value) {
      return (InsertPoster) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "logout".
   *
   * This request holds the parameters needed by the the networkendpoint server.  After setting any
   * optional parameters, call the {@link Logout#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public Logout logout() throws java.io.IOException {
    Logout result = new Logout();
    initialize(result);
    return result;
  }

  public class Logout extends NetworkendpointRequest<Void> {

    private static final String REST_PATH = "logout";

    /**
     * Create a request for the method "logout".
     *
     * This request holds the parameters needed by the the networkendpoint server.  After setting any
     * optional parameters, call the {@link Logout#execute()} method to invoke the remote operation.
     * <p> {@link
     * Logout#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected Logout() {
      super(Networkendpoint.this, "POST", REST_PATH, null, Void.class);
    }

    @Override
    public Logout setAlt(java.lang.String alt) {
      return (Logout) super.setAlt(alt);
    }

    @Override
    public Logout setFields(java.lang.String fields) {
      return (Logout) super.setFields(fields);
    }

    @Override
    public Logout setKey(java.lang.String key) {
      return (Logout) super.setKey(key);
    }

    @Override
    public Logout setOauthToken(java.lang.String oauthToken) {
      return (Logout) super.setOauthToken(oauthToken);
    }

    @Override
    public Logout setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Logout) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Logout setQuotaUser(java.lang.String quotaUser) {
      return (Logout) super.setQuotaUser(quotaUser);
    }

    @Override
    public Logout setUserIp(java.lang.String userIp) {
      return (Logout) super.setUserIp(userIp);
    }

    @Override
    public Logout set(String parameterName, Object value) {
      return (Logout) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "registerUser".
   *
   * This request holds the parameters needed by the the networkendpoint server.  After setting any
   * optional parameters, call the {@link RegisterUser#execute()} method to invoke the remote
   * operation.
   *
   * @param emailAddress
   * @param password
   * @param confirmPassword
   * @return the request
   */
  public RegisterUser registerUser(java.lang.String emailAddress, java.lang.String password, java.lang.String confirmPassword) throws java.io.IOException {
    RegisterUser result = new RegisterUser(emailAddress, password, confirmPassword);
    initialize(result);
    return result;
  }

  public class RegisterUser extends NetworkendpointRequest<ordappengine.ordappengine.networkendpoint.model.RegisterResult> {

    private static final String REST_PATH = "registerUser/{emailAddress}/{password}/{confirmPassword}";

    /**
     * Create a request for the method "registerUser".
     *
     * This request holds the parameters needed by the the networkendpoint server.  After setting any
     * optional parameters, call the {@link RegisterUser#execute()} method to invoke the remote
     * operation. <p> {@link
     * RegisterUser#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param emailAddress
     * @param password
     * @param confirmPassword
     * @since 1.13
     */
    protected RegisterUser(java.lang.String emailAddress, java.lang.String password, java.lang.String confirmPassword) {
      super(Networkendpoint.this, "POST", REST_PATH, null, ordappengine.ordappengine.networkendpoint.model.RegisterResult.class);
      this.emailAddress = com.google.api.client.util.Preconditions.checkNotNull(emailAddress, "Required parameter emailAddress must be specified.");
      this.password = com.google.api.client.util.Preconditions.checkNotNull(password, "Required parameter password must be specified.");
      this.confirmPassword = com.google.api.client.util.Preconditions.checkNotNull(confirmPassword, "Required parameter confirmPassword must be specified.");
    }

    @Override
    public RegisterUser setAlt(java.lang.String alt) {
      return (RegisterUser) super.setAlt(alt);
    }

    @Override
    public RegisterUser setFields(java.lang.String fields) {
      return (RegisterUser) super.setFields(fields);
    }

    @Override
    public RegisterUser setKey(java.lang.String key) {
      return (RegisterUser) super.setKey(key);
    }

    @Override
    public RegisterUser setOauthToken(java.lang.String oauthToken) {
      return (RegisterUser) super.setOauthToken(oauthToken);
    }

    @Override
    public RegisterUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RegisterUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RegisterUser setQuotaUser(java.lang.String quotaUser) {
      return (RegisterUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public RegisterUser setUserIp(java.lang.String userIp) {
      return (RegisterUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String emailAddress;

    /**

     */
    public java.lang.String getEmailAddress() {
      return emailAddress;
    }

    public RegisterUser setEmailAddress(java.lang.String emailAddress) {
      this.emailAddress = emailAddress;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String password;

    /**

     */
    public java.lang.String getPassword() {
      return password;
    }

    public RegisterUser setPassword(java.lang.String password) {
      this.password = password;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String confirmPassword;

    /**

     */
    public java.lang.String getConfirmPassword() {
      return confirmPassword;
    }

    public RegisterUser setConfirmPassword(java.lang.String confirmPassword) {
      this.confirmPassword = confirmPassword;
      return this;
    }

    @Override
    public RegisterUser set(String parameterName, Object value) {
      return (RegisterUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "setBackendSessionToken".
   *
   * This request holds the parameters needed by the the networkendpoint server.  After setting any
   * optional parameters, call the {@link SetBackendSessionToken#execute()} method to invoke the
   * remote operation.
   *
   * @param token
   * @return the request
   */
  public SetBackendSessionToken setBackendSessionToken(java.lang.String token) throws java.io.IOException {
    SetBackendSessionToken result = new SetBackendSessionToken(token);
    initialize(result);
    return result;
  }

  public class SetBackendSessionToken extends NetworkendpointRequest<Void> {

    private static final String REST_PATH = "setBackendSessionToken/{token}";

    /**
     * Create a request for the method "setBackendSessionToken".
     *
     * This request holds the parameters needed by the the networkendpoint server.  After setting any
     * optional parameters, call the {@link SetBackendSessionToken#execute()} method to invoke the
     * remote operation. <p> {@link SetBackendSessionToken#initialize(com.google.api.client.googleapis
     * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param token
     * @since 1.13
     */
    protected SetBackendSessionToken(java.lang.String token) {
      super(Networkendpoint.this, "POST", REST_PATH, null, Void.class);
      this.token = com.google.api.client.util.Preconditions.checkNotNull(token, "Required parameter token must be specified.");
    }

    @Override
    public SetBackendSessionToken setAlt(java.lang.String alt) {
      return (SetBackendSessionToken) super.setAlt(alt);
    }

    @Override
    public SetBackendSessionToken setFields(java.lang.String fields) {
      return (SetBackendSessionToken) super.setFields(fields);
    }

    @Override
    public SetBackendSessionToken setKey(java.lang.String key) {
      return (SetBackendSessionToken) super.setKey(key);
    }

    @Override
    public SetBackendSessionToken setOauthToken(java.lang.String oauthToken) {
      return (SetBackendSessionToken) super.setOauthToken(oauthToken);
    }

    @Override
    public SetBackendSessionToken setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SetBackendSessionToken) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SetBackendSessionToken setQuotaUser(java.lang.String quotaUser) {
      return (SetBackendSessionToken) super.setQuotaUser(quotaUser);
    }

    @Override
    public SetBackendSessionToken setUserIp(java.lang.String userIp) {
      return (SetBackendSessionToken) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String token;

    /**

     */
    public java.lang.String getToken() {
      return token;
    }

    public SetBackendSessionToken setToken(java.lang.String token) {
      this.token = token;
      return this;
    }

    @Override
    public SetBackendSessionToken set(String parameterName, Object value) {
      return (SetBackendSessionToken) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "setStorageManager".
   *
   * This request holds the parameters needed by the the networkendpoint server.  After setting any
   * optional parameters, call the {@link SetStorageManager#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link ordappengine.ordappengine.networkendpoint.model.StorageManager}
   * @return the request
   */
  public SetStorageManager setStorageManager(ordappengine.ordappengine.networkendpoint.model.StorageManager content) throws java.io.IOException {
    SetStorageManager result = new SetStorageManager(content);
    initialize(result);
    return result;
  }

  public class SetStorageManager extends NetworkendpointRequest<Void> {

    private static final String REST_PATH = "setStorageManager";

    /**
     * Create a request for the method "setStorageManager".
     *
     * This request holds the parameters needed by the the networkendpoint server.  After setting any
     * optional parameters, call the {@link SetStorageManager#execute()} method to invoke the remote
     * operation. <p> {@link SetStorageManager#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link ordappengine.ordappengine.networkendpoint.model.StorageManager}
     * @since 1.13
     */
    protected SetStorageManager(ordappengine.ordappengine.networkendpoint.model.StorageManager content) {
      super(Networkendpoint.this, "POST", REST_PATH, content, Void.class);
    }

    @Override
    public SetStorageManager setAlt(java.lang.String alt) {
      return (SetStorageManager) super.setAlt(alt);
    }

    @Override
    public SetStorageManager setFields(java.lang.String fields) {
      return (SetStorageManager) super.setFields(fields);
    }

    @Override
    public SetStorageManager setKey(java.lang.String key) {
      return (SetStorageManager) super.setKey(key);
    }

    @Override
    public SetStorageManager setOauthToken(java.lang.String oauthToken) {
      return (SetStorageManager) super.setOauthToken(oauthToken);
    }

    @Override
    public SetStorageManager setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SetStorageManager) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SetStorageManager setQuotaUser(java.lang.String quotaUser) {
      return (SetStorageManager) super.setQuotaUser(quotaUser);
    }

    @Override
    public SetStorageManager setUserIp(java.lang.String userIp) {
      return (SetStorageManager) super.setUserIp(userIp);
    }

    @Override
    public SetStorageManager set(String parameterName, Object value) {
      return (SetStorageManager) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "signIn".
   *
   * This request holds the parameters needed by the the networkendpoint server.  After setting any
   * optional parameters, call the {@link SignIn#execute()} method to invoke the remote operation.
   *
   * @param emailAddress
   * @param password
   * @return the request
   */
  public SignIn signIn(java.lang.String emailAddress, java.lang.String password) throws java.io.IOException {
    SignIn result = new SignIn(emailAddress, password);
    initialize(result);
    return result;
  }

  public class SignIn extends NetworkendpointRequest<ordappengine.ordappengine.networkendpoint.model.BackendSession> {

    private static final String REST_PATH = "signIn/{emailAddress}/{password}";

    /**
     * Create a request for the method "signIn".
     *
     * This request holds the parameters needed by the the networkendpoint server.  After setting any
     * optional parameters, call the {@link SignIn#execute()} method to invoke the remote operation.
     * <p> {@link
     * SignIn#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
     * be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param emailAddress
     * @param password
     * @since 1.13
     */
    protected SignIn(java.lang.String emailAddress, java.lang.String password) {
      super(Networkendpoint.this, "POST", REST_PATH, null, ordappengine.ordappengine.networkendpoint.model.BackendSession.class);
      this.emailAddress = com.google.api.client.util.Preconditions.checkNotNull(emailAddress, "Required parameter emailAddress must be specified.");
      this.password = com.google.api.client.util.Preconditions.checkNotNull(password, "Required parameter password must be specified.");
    }

    @Override
    public SignIn setAlt(java.lang.String alt) {
      return (SignIn) super.setAlt(alt);
    }

    @Override
    public SignIn setFields(java.lang.String fields) {
      return (SignIn) super.setFields(fields);
    }

    @Override
    public SignIn setKey(java.lang.String key) {
      return (SignIn) super.setKey(key);
    }

    @Override
    public SignIn setOauthToken(java.lang.String oauthToken) {
      return (SignIn) super.setOauthToken(oauthToken);
    }

    @Override
    public SignIn setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SignIn) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SignIn setQuotaUser(java.lang.String quotaUser) {
      return (SignIn) super.setQuotaUser(quotaUser);
    }

    @Override
    public SignIn setUserIp(java.lang.String userIp) {
      return (SignIn) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String emailAddress;

    /**

     */
    public java.lang.String getEmailAddress() {
      return emailAddress;
    }

    public SignIn setEmailAddress(java.lang.String emailAddress) {
      this.emailAddress = emailAddress;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String password;

    /**

     */
    public java.lang.String getPassword() {
      return password;
    }

    public SignIn setPassword(java.lang.String password) {
      this.password = password;
      return this;
    }

    @Override
    public SignIn set(String parameterName, Object value) {
      return (SignIn) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateStatus".
   *
   * This request holds the parameters needed by the the networkendpoint server.  After setting any
   * optional parameters, call the {@link UpdateStatus#execute()} method to invoke the remote
   * operation.
   *
   * @param blobKey
   * @param status
   * @return the request
   */
  public UpdateStatus updateStatus(java.lang.String blobKey, java.lang.String status) throws java.io.IOException {
    UpdateStatus result = new UpdateStatus(blobKey, status);
    initialize(result);
    return result;
  }

  public class UpdateStatus extends NetworkendpointRequest<Void> {

    private static final String REST_PATH = "void/{blobKey}/{status}";

    /**
     * Create a request for the method "updateStatus".
     *
     * This request holds the parameters needed by the the networkendpoint server.  After setting any
     * optional parameters, call the {@link UpdateStatus#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateStatus#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param blobKey
     * @param status
     * @since 1.13
     */
    protected UpdateStatus(java.lang.String blobKey, java.lang.String status) {
      super(Networkendpoint.this, "PUT", REST_PATH, null, Void.class);
      this.blobKey = com.google.api.client.util.Preconditions.checkNotNull(blobKey, "Required parameter blobKey must be specified.");
      this.status = com.google.api.client.util.Preconditions.checkNotNull(status, "Required parameter status must be specified.");
    }

    @Override
    public UpdateStatus setAlt(java.lang.String alt) {
      return (UpdateStatus) super.setAlt(alt);
    }

    @Override
    public UpdateStatus setFields(java.lang.String fields) {
      return (UpdateStatus) super.setFields(fields);
    }

    @Override
    public UpdateStatus setKey(java.lang.String key) {
      return (UpdateStatus) super.setKey(key);
    }

    @Override
    public UpdateStatus setOauthToken(java.lang.String oauthToken) {
      return (UpdateStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateStatus setQuotaUser(java.lang.String quotaUser) {
      return (UpdateStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateStatus setUserIp(java.lang.String userIp) {
      return (UpdateStatus) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String blobKey;

    /**

     */
    public java.lang.String getBlobKey() {
      return blobKey;
    }

    public UpdateStatus setBlobKey(java.lang.String blobKey) {
      this.blobKey = blobKey;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String status;

    /**

     */
    public java.lang.String getStatus() {
      return status;
    }

    public UpdateStatus setStatus(java.lang.String status) {
      this.status = status;
      return this;
    }

    @Override
    public UpdateStatus set(String parameterName, Object value) {
      return (UpdateStatus) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "uploadPoster".
   *
   * This request holds the parameters needed by the the networkendpoint server.  After setting any
   * optional parameters, call the {@link UploadPoster#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link ordappengine.ordappengine.networkendpoint.model.PosterFile}
   * @return the request
   */
  public UploadPoster uploadPoster(ordappengine.ordappengine.networkendpoint.model.PosterFile content) throws java.io.IOException {
    UploadPoster result = new UploadPoster(content);
    initialize(result);
    return result;
  }

  public class UploadPoster extends NetworkendpointRequest<ordappengine.ordappengine.networkendpoint.model.UploadResult> {

    private static final String REST_PATH = "uploadPoster";

    /**
     * Create a request for the method "uploadPoster".
     *
     * This request holds the parameters needed by the the networkendpoint server.  After setting any
     * optional parameters, call the {@link UploadPoster#execute()} method to invoke the remote
     * operation. <p> {@link
     * UploadPoster#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link ordappengine.ordappengine.networkendpoint.model.PosterFile}
     * @since 1.13
     */
    protected UploadPoster(ordappengine.ordappengine.networkendpoint.model.PosterFile content) {
      super(Networkendpoint.this, "POST", REST_PATH, content, ordappengine.ordappengine.networkendpoint.model.UploadResult.class);
    }

    @Override
    public UploadPoster setAlt(java.lang.String alt) {
      return (UploadPoster) super.setAlt(alt);
    }

    @Override
    public UploadPoster setFields(java.lang.String fields) {
      return (UploadPoster) super.setFields(fields);
    }

    @Override
    public UploadPoster setKey(java.lang.String key) {
      return (UploadPoster) super.setKey(key);
    }

    @Override
    public UploadPoster setOauthToken(java.lang.String oauthToken) {
      return (UploadPoster) super.setOauthToken(oauthToken);
    }

    @Override
    public UploadPoster setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UploadPoster) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UploadPoster setQuotaUser(java.lang.String quotaUser) {
      return (UploadPoster) super.setQuotaUser(quotaUser);
    }

    @Override
    public UploadPoster setUserIp(java.lang.String userIp) {
      return (UploadPoster) super.setUserIp(userIp);
    }

    @Override
    public UploadPoster set(String parameterName, Object value) {
      return (UploadPoster) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Networkendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Networkendpoint}. */
    @Override
    public Networkendpoint build() {
      return new Networkendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link NetworkendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setNetworkendpointRequestInitializer(
        NetworkendpointRequestInitializer networkendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(networkendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
